"""create data

Revision ID: cce012a86213
Revises: 
Create Date: 2021-06-08 12:52:42.621984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce012a86213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obat', sa.Column('kondisi', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obat', 'kondisi')
    # ### end Alembic commands ###
